### PR TITLE
Files with extension ".orbit" should not be picked up from classpath,…

### PR DESCRIPTION
**Pull request by rkrisztian**
… as that is an unknown url type for commons-vfs2.

### CODE REVIEW

**Comment by stoicflame** [comment]
@jskovjyskebankdk, can you take a look at this PR? 

I'm a little hesitant to accept it because there may be artifacts on the classpath that _don't_ end in `.jar`. For example, I've seen some dependencies come with the `.bundle` extension, indicating an OSGi bundle.

**Comment by rkrisztian** [comment]
Valid point. This is what the Maven plugin does:

```
  /**
   * List of all supported packaging types
   */
  private static final List<String> SUPPORTED_TYPES = Arrays.asList("jar", "bundle", "eclipse-plugin", "ejb", "ejb-client");
```

And then later:

```
      if (!SUPPORTED_TYPES.contains(type)) {
        //remove the non-jars from the classpath.
        if (getLog().isDebugEnabled()) {
          Iterator<String> typesIt = SUPPORTED_TYPES.iterator();
          String types = "";
          while (typesIt.hasNext()) {
            types += "'" + typesIt.next() + (typesIt.hasNext() ? "', " : "'");
          }
          getLog().debug("[ENUNCIATE] Artifact " + artifact + " will be removed from the enunciate classpath because it's of type '" + type + "' and not of type " + types + ".");
```

**Comment by jskov-jyskebank-dk** [comment]
I think it would be sensible to change to a positive list, containing the Maven defaults.
@rkrisztian would you give it a shot?

**Comment by jskov-jyskebank-dk** [comment]
I have made a fix similar to this PR.
Not sure why I never got around to it back in 2017. My apologies.

**Pull request closed without merging**
